# TRAITEMENT DE DONNÉES

# Modélisation des causes et les caractéristiques des accidents pour réduire leur nombre et leur gravité

En statistique et en Machine Learning, la variable cible (ou target) est celle que l'on cherche à prédire ou à expliquer en fonction de toutes les autres (les variables explicatives). Donc La gravité **grav** est la variable idéale pour expliquer les facteurs liés à l'accident survenu.

C'est sur cette variable que se basent les politiques publiques.

- Si mon modèle va montrer que la combinaison "Pluie" (atm) + "Route départementale" (catr), etc... augmente drastiquement la gravité, l'État peut décider d'abaisser la vitesse maximale (vma) sur ces zones précises.

## Importation des librairies

In [10]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import fisher_exact
from scipy.stats import chi2_contingency
from sklearn.model_selection import train_test_split

## Importation des bases de données

In [6]:
def nettoyer_colonnes(df):

    """

    Nettoie les noms de colonnes d'un DataFrame.
 
    Transformations appliquées :

    - mise en minuscules

    - remplacement des points (.) par des underscores (_)

    """
 
    # Nettoyage des noms de colonnes

    df.columns = (

        df.columns

            .str.lower()                     # tout en minuscules

            .str.replace('.', '_')           # remplace les points par _

    )
 
    return df

* **Base caracteristique**

In [3]:
df_caract = pd.read_csv("caracteristique.txt", sep="\t")  # sep="," si CSV classique
df_caract.head(10)

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,col,adr,lat,long
0,202100037733,28,5,2021,14:15,1,CC_97407,2,2,1,3,JEAN MOULIN (RUE) - RIV. DES GALETS,"-20,95888","55,31743"
1,202100049382,2,3,2021,10:59,1,CC_63113,2,1,1,2,SAINT ROBERT (RUE),"45,79137","3,1162"
2,202100038891,20,5,2021,16:50,1,CC_88160,2,2,1,1,POISSOMPRE (FG DE),"48,18261","6,47218"
3,202100028616,14,7,2021,19:45,1,CC_80021,2,1,1,3,CAGNARD (RUE),"49,90355","2,2872"
4,202100033509,17,6,2021,23:40,3,CC_13214,2,1,1,1,A7-Sens Lyon vers Marseille,"43,34031","5,37689"
5,202100048274,12,3,2021,16:25,1,CC_30189,2,2,1,6,TALABOT (BOULEVARD),"43,83843726","4,372475088"
6,202100054416,18,1,2021,15:25,1,CC_91228,2,3,1,2,BD CHAMPS ELYSEES,"48,633158","2,425203"
7,202100026295,29,7,2021,17:35,1,CC_51230,2,1,1,7,Rue Pierre Semard,"49,04566","3,96145"
8,202100010947,26,10,2021,09:10,1,CC_93059,2,3,1,3,MERCHER (PASSAGE),"48,94933","2,35775"
9,202100009689,4,11,2021,08:35,1,CC_55369,1,1,5,6,D28,"48,808277","5,211725"

In [4]:
# Cette commande détecte automatiquement si une colonne doit être int, string, objet ou boolean
df_caract = df_caract.convert_dtypes()

In [5]:
def explore_base(df_caract):
    print("\033[1mFormat\033[0m")
    print("----------------------------------")
    print(df_caract.info())
    print("----------------------------------")
    print("\033[1mContrôle des valeurs manquantes\033[0m")
    print("----------------------------------")
    print(df_caract.isna().sum().sort_values(ascending=False))

    for i in df_caract.columns:
        if df_caract[i].dtypes in ['int64','float64']:
            print("----------------------------------")
            print("\033[1m Variable :\033[0m",i)
            print("----------------------------------")
            print("\033[1m Description \033[0m")
            print("----------------------------------\n")
            print(df_caract[i].describe())
            print("----------------------------------")
            print("\033[1m Modalité \033[0m")
            print("----------------------------------\n")
            print(df_caract[i].unique())

        else:
            print("----------------------------------")
            print("\033[1m Variable : \033[0m",i)
            print("----------------------------------")
            print("\033[1m Description \033[0m")
            print("----------------------------------\n")
            print(df_caract[i].value_counts(dropna=False))

In [13]:
explore_base(df_caract)

Format
----------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56530 entries, 0 to 56529
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  56530 non-null  int64
 1   jour     56530 non-null  int64
 2   mois     56530 non-null  int64
 3   an       56530 non-null  int64
 4   hrmn     56530 non-null  object
 5   lum      56530 non-null  int64
 6   com      56530 non-null  object
 7   agg      56530 non-null  int64
 8   int      56530 non-null  int64
 9   atm      56530 non-null  int64
 10  col      56530 non-null  int64
 11  adr      55957 non-null  object
 12  lat      56530 non-null  object
 13  long     56530 non-null  object
dtypes: int64(9), object(5)
memory usage: 6.0+ MB
None
----------------------------------
Contrôle des valeurs manquantes
----------------------------------
adr        573
Num_Acc      0
jour         0
mois         0
an           0
hrmn         0
lum          0
com          0
agg          0
int          0
atm          0
col          0
lat          0
long         0
dtype: int64
----------------------------------
 Variable : Num_Acc
----------------------------------
 Description
----------------------------------

count    5.653000e+04
mean     2.021000e+11
std      1.631541e+04
min      2.021000e+11
25%      2.021000e+11
50%      2.021000e+11
75%      2.021000e+11
max      2.021001e+11
Name: Num_Acc, dtype: float64
----------------------------------
 Modalité
----------------------------------

[202100037733 202100049382 202100038891 ... 202100016048 202100039830
 202100046742]
----------------------------------
 Variable : jour
----------------------------------
 Description
----------------------------------

count    56530.000000
mean        15.764408
std          8.794143
min          1.000000
25%          8.000000
50%         16.000000
75%         23.000000
max         31.000000
Name: jour, dtype: float64
----------------------------------
 Modalité
----------------------------------

[28  2 20 14 17 12 18 29 26  4  3 23 24 30 31  5 13 10 22 19  9 16  6 25
 11  7  8  1 15 27 21]
----------------------------------
 Variable : mois
----------------------------------
 Description
----------------------------------

count    56530.000000
mean         6.866903
std          3.295166
min          1.000000
25%          4.000000
50%          7.000000
75%         10.000000
max         12.000000
Name: mois, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 5  3  7  6  1 10 11  8  9 12  2  4]
----------------------------------
 Variable : an
----------------------------------
 Description
----------------------------------

count    56530.0
mean      2021.0
std          0.0
min       2021.0
25%       2021.0
50%       2021.0
75%       2021.0
max       2021.0
Name: an, dtype: float64
----------------------------------
 Modalité
----------------------------------

[2021]
----------------------------------
 Variable :  hrmn
----------------------------------
 Description
----------------------------------

hrmn
18:00    769
17:00    707
17:30    653
18:30    630
16:00    613
        ...
13:31      1
04:12      1
02:16      1
03:11      1
04:06      1
Name: count, Length: 1374, dtype: int64
----------------------------------
 Variable : lum
----------------------------------
 Description
----------------------------------

count    56530.000000
mean         1.835309
std          1.437554
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          5.000000
Name: lum, dtype: float64
----------------------------------
 Modalité
----------------------------------

[1 3 5 2 4]
----------------------------------
 Variable :  com
----------------------------------
 Description
----------------------------------

com
CC_75116    507
CC_75112    434
CC_75119    384
CC_97302    378
CC_75115    368
           ...
CC_45081      1
CC_81010      1
CC_62310      1
CC_38163      1
CC_62898      1
Name: count, Length: 11150, dtype: int64
----------------------------------
 Variable : agg
----------------------------------
 Description
----------------------------------

count    56530.000000
mean         1.642579
std          0.479244
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: agg, dtype: float64
----------------------------------
 Modalité
----------------------------------

[2 1]
----------------------------------
 Variable : int
----------------------------------
 Description
----------------------------------

count    56530.000000
mean         2.077198
std          2.019939
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          9.000000
Name: int, dtype: float64
----------------------------------
 Modalité
----------------------------------

[2 1 3 4 9 5 6 7 8]
----------------------------------
 Variable : atm
----------------------------------
 Description
----------------------------------

count    56530.000000
mean         1.623651
std          1.707141
min         -1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          9.000000
Name: atm, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 1  5  2  8  7  4  3  9  6 -1]
----------------------------------
 Variable : col
----------------------------------
 Description
----------------------------------

count    56530.000000
mean         4.004723
std          1.962796
min         -1.000000
25%          3.000000
50%          3.000000
75%          6.000000
max          7.000000
Name: col, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 3  2  1  6  7  4  5 -1]
----------------------------------
 Variable :  adr
----------------------------------
 Description
----------------------------------

adr
NaN                             573
AUTOROUTE A86                   351
AUTOROUTE A1                    244
A4                              241
AUTOROUTE A3                    223
                               ...
10 Rue d Uttenhoffen              1
Rue de l Epinetterie              1
A7, pk 239+000 sens sud/nord      1
face au 400 rue du haut           1
HAIE. RUE DE LA                   1
Name: count, Length: 29669, dtype: int64
----------------------------------
 Variable :  lat
----------------------------------
 Description
----------------------------------

lat
-17,584522     11
48,8           10
48,88189        7
43,3            7
43,33           6
               ..
16,21747        1
49,900771       1
49,203931       1
48,92587        1
49,46523106     1
Name: count, Length: 54612, dtype: int64
----------------------------------
 Variable :  long
----------------------------------
 Description
----------------------------------

long
-149,568578    11
2,26872         7
2,386589        6
5,39            6
2,37            6
               ..
2,042663097     1
5,58569         1
4,628414765     1
3,271415        1
1,112713775     1
Name: count, Length: 54920, dtype: int64

* **Base Lieux**

In [33]:
df_lieux = pd.read_excel("lieux.xls")
df_lieux.head(10)

,Num_Acc,dep,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
0,202100022009,40,1,A63,0,A,3,3,0,1,141,600,1,NaN,-1.0,1,0,1,130
1,202100023746,94,4,VLADIMIR ILLITCH LENINE (AV),0,NaN,-1,2,0,1,0,0,1,NaN,-1.0,1,0,1,50
2,202100019549,2A,2,20,0,T,2,2,0,1,-1,-1,2,NaN,-1.0,1,0,3,80
3,202100022748,75,4,AVENUE SIMON BOLIVAR,0,NaN,2,2,0,2,-1,-1,1,NaN,-1.0,1,0,1,50
4,202100051993,971,3,BOLOGNE (ROUTE DE),0,NaN,2,2,0,1,-1,-1,1,NaN,-1.0,1,0,1,50
5,202100038809,57,3,63,0,A,2,2,0,1,-1,170,1,NaN,-1.0,2,0,1,50
6,202100023370,971,4,NaN,0,NaN,2,1,1,1,-1,-1,1,NaN,3.0,1,0,3,50
7,202100038829,17,3,939,-1,NaN,2,2,0,1,28,659,1,NaN,-1.0,2,0,1,80
8,202100013461,66,3,916,0,NaN,2,2,0,1,6,645,1,NaN,-1.0,1,0,1,70
9,202100017993,78,3,GENERAL DE GAULLE (RUE DU),0,NaN,-1,0,0,1,38,662,1,NaN,-1.0,1,9,1,50

In [10]:
# Cette commande détecte automatiquement si une colonne doit être int, string, objet ou boolean
df_lieux = df_lieux.convert_dtypes()

In [38]:
def explore_base(df_lieux):
    print("\033[1mFormat\033[0m")
    print("----------------------------------")
    print(df_lieux.info())
    print("----------------------------------")
    print("\033[1mContrôle des valeurs manquantes\033[0m")
    print("----------------------------------")
    print(df_lieux.isna().sum().sort_values(ascending=False))

    for i in df_lieux.columns:
        if df_lieux[i].dtypes in ['int64','float64']:
            print("----------------------------------")
            print("\033[1m Variable :\033[0m",i)
            print("----------------------------------")
            print("\033[1m Description \033[0m")
            print("----------------------------------\n")
            print(df_lieux[i].describe())
            print("----------------------------------")
            print("\033[1m Modalité \033[0m")
            print("----------------------------------\n")
            print(df_lieux[i].unique())

        else:
            print("----------------------------------")
            print("\033[1m Variable : \033[0m",i)
            print("----------------------------------")
            print("\033[1m Description \033[0m")
            print("----------------------------------\n")
            print(df_lieux[i].value_counts(dropna=False))

In [39]:
explore_base(df_lieux)

Format
----------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56525 entries, 0 to 56524
Data columns (total 19 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  56525 non-null  int64
 1   dep      56525 non-null  object
 2   catr     56525 non-null  int64
 3   voie     52117 non-null  object
 4   v1       56525 non-null  int64
 5   v2       4990 non-null   object
 6   circ     56525 non-null  int64
 7   nbv      56525 non-null  int64
 8   vosp     56525 non-null  int64
 9   prof     56525 non-null  int64
 10  pr       56525 non-null  int64
 11  pr1      56525 non-null  int64
 12  plan     56525 non-null  int64
 13  lartpc   108 non-null    float64
 14  larrout  56525 non-null  float64
 15  surf     56525 non-null  int64
 16  infra    56525 non-null  int64
 17  situ     56525 non-null  int64
 18  vma      56525 non-null  int64
dtypes: float64(2), int64(14), object(3)
memory usage: 8.2+ MB
None
----------------------------------
Contrôle des valeurs manquantes
----------------------------------
lartpc     56417
v2         51535
voie        4408
Num_Acc        0
pr1            0
situ           0
infra          0
surf           0
larrout        0
plan           0
prof           0
pr             0
dep            0
vosp           0
nbv            0
circ           0
v1             0
catr           0
vma            0
dtype: int64
----------------------------------
 Variable : Num_Acc
----------------------------------
 Description
----------------------------------

count    5.652500e+04
mean     2.021000e+11
std      1.631533e+04
min      2.021000e+11
25%      2.021000e+11
50%      2.021000e+11
75%      2.021000e+11
max      2.021001e+11
Name: Num_Acc, dtype: float64
----------------------------------
 Modalité
----------------------------------

[202100022009 202100023746 202100019549 ... 202100047332 202100016135
 202100017773]
----------------------------------
 Variable :  dep
----------------------------------
 Description
----------------------------------

dep
75     5070
93     2897
13     2780
94     2493
69     2444
       ...
90       43
978      40
977      22
986      13
975       5
Name: count, Length: 107, dtype: int64
----------------------------------
 Variable : catr
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         3.422256
std          1.329629
min          1.000000
25%          3.000000
50%          3.000000
75%          4.000000
max          9.000000
Name: catr, dtype: float64
----------------------------------
 Modalité
----------------------------------

[1 4 2 3 7 9 6 5]
----------------------------------
 Variable :  voie
----------------------------------
 Description
----------------------------------

voie
NaN                           4408
1                              442
7                              393
2                              320
AUTOROUTE A86                  298
                              ...
SOMME (AVE DE LA)                1
796                              1
CHEVALIER (AVENUE MAURICE)       1
LEROUX (R)                       1
SERGENT BERNES CAMBOT DU         1
Name: count, Length: 17239, dtype: int64
----------------------------------
 Variable : v1
----------------------------------
 Description
----------------------------------

count    56525.000000
mean        -0.169978
std          0.392071
min         -1.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          3.000000
Name: v1, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 0 -1  2  3]
----------------------------------
 Variable :  v2
----------------------------------
 Description
----------------------------------

v2
NaN    51535
D       3164
A        896
N        225
C        119
E        106
R         92
B         85
M         74
 -        67
T         43
F         24
X         15
V         14
O         12
U          9
G          8
S          7
Z          6
L          5
P          5
H          3
K          3
J          3
W          2
I          2
34         1
Name: count, dtype: int64
----------------------------------
 Variable : circ
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         1.801521
std          0.905681
min         -1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          4.000000
Name: circ, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 3 -1  2  1  4]
----------------------------------
 Variable : nbv
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         2.381884
std          1.378039
min         -1.000000
25%          2.000000
50%          2.000000
75%          3.000000
max         12.000000
Name: nbv, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 3  2  1  0  5  4  7  6 -1  8 10  9 11 12]
----------------------------------
 Variable : vosp
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         0.211517
std          0.669808
min         -1.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          3.000000
Name: vosp, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 0  1 -1  2  3]
----------------------------------
 Variable : prof
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         1.236214
std          0.545795
min         -1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: prof, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 1  2  4  3 -1]
----------------------------------
 Variable : pr
----------------------------------
 Description
----------------------------------

count    56525.000000
mean        14.536877
std         64.534147
min         -1.000000
25%         -1.000000
50%          0.000000
75%         10.000000
max       5220.000000
Name: pr, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 141    0   -1   28    6   38  132    3    1    8    4   71   15   14
   37   11   18  101   45    2   68   51   22   23   17   21    9   44
   40    5   79   29    7   20   10   41   67   47   25   32   19   24
   57   12   26  336   30  121   60   61  289   58  274   43   42   39
   81   70   73  201  111   36   62   33  285  198   59  100   34   53
   13   16   75  268   63   50  265  112   35   90   27   76   72   46
   89   48   98  227  428  414  390   55  162   92  260   80  135  104
   56  277   54   85  283   31  177  387  448   49  138   91   86  103
  125  267  180  116   99  302  102  262  216   69   78  259   65  168
  315   88  105   74  153   87  304   52  256  538  173  113  261  374
  253   83   94  269   93   66  473  158  266  120  142   77  300   64
   97  254   82  131  107   96 1640  530  189  114  276  117  271  534
  118  228  205  275  313  236  207  156  327 1000  537  137  159  250
  528  368  179  324  281  155  148  185  323  249  230  110   95  326
  242  381  199  247  373  257  424  542  143  169  235  186  130  109
  115  119  124  455 2012  213  233  127  499  317  264  243  432  301
  145  535  191  166  540  297  533  292  444  170  106  279  126 5220
  278  136  229  273  197  234  453  108  187  298  406  163  295 4359
  204  258  150  416  210  270  167  248 1100  999  226  420  452   84
  133  352  282  200  351  466  291  188  321  435  183  194  164  402
  202  147  195  182  252  310  284  272  146  411  154  206  239  214
  348  161  129  454  341  238  140  433  356  344  398  531  446  375
  123  286  456  181  308  437  144  470  349  544  529  400  290  311
  152  128  532  211  306  663  255  219  193  192  196  223  299  237
  350  363  421  550  343  151  221  357  558  472  122  217  434  403
  410  338  354  149  171  541  370  385  438  157  415  231  426  319
  331  548  222  134  325  512  409  208  419 3697  225  139  500  316
  232  367  427  165  280  176  244 1230  224  382  288 4100  246  294
  203  358  536  539 2749 1004  220  391  365  309  376  240  362 1111
  359  447  174  305  263  347  412 1212  913  342  333 2924  767  422
  190  396  353  401  209  215  431  510  355  449  172  405  334  462
  394  360 3330  429  335  218  175  178 1015  441  329  330  160  212
  303  184  874  287  430  733  561  494  296]
----------------------------------
 Variable : pr1
----------------------------------
 Description
----------------------------------

count    56525.000000
mean       179.293392
std        300.720914
min         -1.000000
25%         -1.000000
50%          0.000000
75%        300.000000
max       8347.000000
Name: pr1, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 600    0   -1 ... 1078  338  616]
----------------------------------
 Variable : plan
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         1.309385
std          0.684367
min         -1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: plan, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 1  2  3  4 -1]
----------------------------------
 Variable : lartpc
----------------------------------
 Description
----------------------------------

count    108.000000
mean       1.549074
std        4.485959
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max       40.000000
Name: lartpc, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ nan  0.   2.5  6.5  0.8  6.   6.3  1.6  4.   2.7 12.5  3.5  6.1  3.
  4.5  6.8 40.   3.7  2.8 13. ]
----------------------------------
 Variable : larrout
----------------------------------
 Description
----------------------------------

count    56525.000000
mean        -0.716479
std          1.364933
min         -1.000000
25%         -1.000000
50%         -1.000000
75%         -1.000000
max         30.000000
Name: larrout, dtype: float64
----------------------------------
 Modalité
----------------------------------

[-1.    3.    7.    5.    4.    5.5   4.6   6.    3.5   7.2   5.8   3.6
  9.3  10.    0.    6.3   6.2  14.   10.5   6.15  5.6  13.5   4.4   3.9
 17.5  10.3   8.8  16.   13.    7.3   7.8  10.2   4.7   2.5   4.2   3.3
  9.    4.3  11.    6.8   3.4   4.8   5.4   7.6  11.5   4.5   4.75 10.4
 12.    5.3  11.6   6.7  12.4  20.   19.    9.5  15.    1.4  11.4   6.5
  8.5   6.4   5.2  10.8  30.    8.4   4.15  3.8   7.7   7.4   7.5   2.9
  9.4   6.6   2.4   2.6   5.1   5.7   8.2  14.5   4.9   8.    5.15  4.1
 12.7   3.2   8.3 ]
----------------------------------
 Variable : surf
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         1.278744
std          0.873684
min         -1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          9.000000
Name: surf, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 1  2  3  8  9  4  5  7 -1  6]
----------------------------------
 Variable : infra
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         0.779531
std          2.148660
min         -1.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          9.000000
Name: infra, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 0  9  1  5  4  3  2 -1  8  6  7]
----------------------------------
 Variable : situ
----------------------------------
 Description
----------------------------------

count    56525.000000
mean         1.611181
std          1.572671
min         -1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          8.000000
Name: situ, dtype: float64
----------------------------------
 Modalité
----------------------------------

[ 1  3  4  8  5  6  2 -1]
----------------------------------
 Variable : vma
----------------------------------
 Description
----------------------------------

count    56525.000000
mean        59.010243
std         25.504129
min         -1.000000
25%         50.000000
50%         50.000000
75%         80.000000
max        901.000000
Name: vma, dtype: float64
----------------------------------
 Modalité
----------------------------------

[130  50  80  70  90  30 110   2  -1  10  60   5  40  20   1   6  45  25
 100  15  55 500 770   9 900 520 140 300  75 180 700  12   3 501 502   8
 901]

* **Base usagers**

In [135]:
df_usag = pd.read_csv("usagers.csv")
df_usag.head(10)

,Num_Acc,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,202100021165,163Â 830,A01,9,2,4,1,1948.0,0,1,-1,-1,0,0,-1
1,202100020281,165Â 383,A01,1,1,1,2,1965.0,1,1,8,-1,-1,-1,-1
2,202100047336,117Â 153,A01,1,1,4,2,1972.0,0,2,0,-1,-1,-1,-1
3,202100008918,185Â 779,B01,1,1,4,1,1985.0,9,8,0,-1,-1,-1,-1
4,202100009175,185Â 315,A01,1,1,3,1,1960.0,5,1,-1,-1,0,0,-1
5,202100050277,111Â 849,B01,1,1,4,1,1972.0,3,1,9,-1,0,0,-1
6,202100027012,153Â 433,A01,1,1,1,1,1986.0,5,1,-1,-1,0,0,-1
7,202100028064,151Â 549,A01,1,1,1,2,1957.0,5,1,-1,-1,0,0,-1
8,202100003701,195Â 137,A01,1,1,4,2,2006.0,0,2,0,-1,-1,-1,-1
9,202100033813,141Â 320,A01,1,1,1,1,1999.0,5,1,8,-1,-1,-1,-1

In [136]:
df_usag.shape

(129189, 15)

In [137]:
df_usag.isna().sum()

Num_Acc           0
id_vehicule       0
num_veh           0
place             0
catu              0
grav              0
sexe              0
an_nais        3067
trajet            0
secu1             0
secu2             0
secu3             0
locp              0
actp              0
etatp             0
dtype: int64

In [145]:
df_usag[df_usag['an_nais'].isna()].sort_values('id_vehicule')

,Num_Acc,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
127037,202100056500,100Â 909,A01,1,1,1,-1,NaN,-1,-1,-1,-1,-1,-1,-1
18360,202100056487,100Â 930,Z01,1,1,1,-1,NaN,-1,0,0,0,-1,-1,-1
25321,202100056485,100Â 935,Z01,1,1,1,-1,NaN,-1,-1,-1,-1,-1,-1,-1
66525,202100056472,100Â 959,B01,1,1,1,-1,NaN,-1,-1,-1,-1,-1,-1,-1
8253,202100056439,101Â 015,A01,1,1,1,-1,NaN,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93622,202100000051,201Â 657,B01,1,1,1,-1,NaN,-1,-1,-1,-1,-1,-1,-1
8488,202100000045,201Â 676,A01,1,1,1,-1,NaN,-1,-1,-1,-1,-1,-1,-1
48815,202100000038,201Â 694,A01,1,1,1,-1,NaN,-1,8,-1,-1,0,0,-1
52373,202100000020,201Â 725,A01,1,1,1,-1,NaN,-1,-1,-1,-1,-1,-1,-1
53845,202100000005,201Â 755,Z01,1,1,-1,-1,NaN,-1,8,-1,-1,-1,-1,-1

In [150]:
df_usag.dropna(subset=['an_nais'], inplace=True)

In [173]:
#df_usag[df_usag['sexe']==-1].sort_values('id_vehicule')

In [172]:
df_usag[df_usag['sexe'].isin([0, -1])]

,Num_Acc,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
49978,202100021078,163A 980,B01,1,1,1,-1,1993,-1,8,8,8,0,0,-1
56737,202100034601,139A 865,A01,1,1,1,-1,1992,-1,8,8,8,0,0,-1

In [174]:
df_usag = df_usag[~df_usag['sexe'].isin([0, -1])]

In [176]:
# 1) Corriger les caractères dans id_vehicule
df_usag["id_vehicule"] = df_usag["id_vehicule"].str.replace("Â", "A", regex=False)

# 2) Supprimer le .0 dans an_nais (ex: 1948.0 → 1948)
df_usag["an_nais"] = df_usag["an_nais"].astype("Int64")
df_usag.head(10)

/var/folders/yp/sy_lpvd138s8qtlhb_yrqtjm0000gn/T/ipykernel_14118/1899422222.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_usag["id_vehicule"] = df_usag["id_vehicule"].str.replace("Â", "A", regex=False)
/var/folders/yp/sy_lpvd138s8qtlhb_yrqtjm0000gn/T/ipykernel_14118/1899422222.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_usag["an_nais"] = df_usag["an_nais"].astype("Int64")

,Num_Acc,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,202100021165,163A 830,A01,9,2,4,1,1948,0,1,-1,-1,0,0,-1
1,202100020281,165A 383,A01,1,1,1,2,1965,1,1,8,-1,-1,-1,-1
2,202100047336,117A 153,A01,1,1,4,2,1972,0,2,0,-1,-1,-1,-1
3,202100008918,185A 779,B01,1,1,4,1,1985,9,8,0,-1,-1,-1,-1
4,202100009175,185A 315,A01,1,1,3,1,1960,5,1,-1,-1,0,0,-1
5,202100050277,111A 849,B01,1,1,4,1,1972,3,1,9,-1,0,0,-1
6,202100027012,153A 433,A01,1,1,1,1,1986,5,1,-1,-1,0,0,-1
7,202100028064,151A 549,A01,1,1,1,2,1957,5,1,-1,-1,0,0,-1
8,202100003701,195A 137,A01,1,1,4,2,2006,0,2,0,-1,-1,-1,-1
9,202100033813,141A 320,A01,1,1,1,1,1999,5,1,8,-1,-1,-1,-1

In [178]:
# Cette commande détecte automatiquement si une colonne doit être int, string, objet ou boolean
df_usag = df_usag.convert_dtypes()

In [179]:
def explore_base(df_usag):
    print("\033[1mFormat\033[0m")
    print("----------------------------------")
    print(df_usag.info())
    print("----------------------------------")
    print("\033[1mContrôle des valeurs manquantes\033[0m")
    print("----------------------------------")
    print(df_usag.isna().sum().sort_values(ascending=False))

    for i in df_usag.columns:
        if df_usag[i].dtypes in ['int64','float64']:
            print("----------------------------------")
            print("\033[1m Variable :\033[0m",i)
            print("----------------------------------")
            print("\033[1m Description \033[0m")
            print("----------------------------------\n")
            print(df_usag[i].describe())
            print("----------------------------------")
            print("\033[1m Modalité \033[0m")
            print("----------------------------------\n")
            print(df_usag[i].unique())

        else:
            print("----------------------------------")
            print("\033[1m Variable : \033[0m",i)
            print("----------------------------------")
            print("\033[1m Description \033[0m")
            print("----------------------------------\n")
            print(df_usag[i].value_counts(dropna=False))

In [180]:
explore_base(df_usag)

Format
----------------------------------
<class 'pandas.core.frame.DataFrame'>
Index: 126120 entries, 0 to 129188
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Num_Acc      126120 non-null  Int64
 1   id_vehicule  126120 non-null  string
 2   num_veh      126120 non-null  string
 3   place        126120 non-null  Int64
 4   catu         126120 non-null  Int64
 5   grav         126120 non-null  Int64
 6   sexe         126120 non-null  Int64
 7   an_nais      126120 non-null  Int64
 8   trajet       126120 non-null  Int64
 9   secu1        126120 non-null  Int64
 10  secu2        126120 non-null  Int64
 11  secu3        126120 non-null  Int64
 12  locp         126120 non-null  Int64
 13  actp         126120 non-null  string
 14  etatp        126120 non-null  Int64
dtypes: Int64(12), string(3)
memory usage: 16.8 MB
None
----------------------------------
Contrôle des valeurs manquantes
----------------------------------
Num_Acc        0
id_vehicule    0
num_veh        0
place          0
catu           0
grav           0
sexe           0
an_nais        0
trajet         0
secu1          0
secu2          0
secu3          0
locp           0
actp           0
etatp          0
dtype: int64
----------------------------------
 Variable :  Num_Acc
----------------------------------
 Description
----------------------------------

Num_Acc
202100003154    24
202100050118    21
202100047872    21
202100023738    18
202100016415    17
                ..
202100029115     1
202100043256     1
202100045511     1
202100052617     1
202100056521     1
Name: count, Length: 56521, dtype: Int64
----------------------------------
 Variable :  id_vehicule
----------------------------------
 Description
----------------------------------

id_vehicule
196A 125    21
172A 295    17
169A 915    16
131A 903    14
155A 083    14
            ..
195A 207     1
176A 536     1
178A 171     1
176A 063     1
169A 018     1
Name: count, Length: 95188, dtype: Int64
----------------------------------
 Variable :  num_veh
----------------------------------
 Description
----------------------------------

num_veh
A01     75822
B01     43024
C01      4894
D01      1072
Z01       635
E01       341
F01        88
Y01        67
G01        40
H01        20
T01        15
I01        11
J01         9
K01         7
TA01        6
SA01        5
FA01        5
M01         5
L01         5
V01         4
P01         3
[01         3
BA01        3
RA01        3
AA01        3
KA01        2
DA01        2
X01         2
MB01        2
CA01        2
]01         1
NA01        1
IA01        1
LA01        1
SB01        1
N01         1
GB01        1
VB01        1
KD01        1
EB01        1
YA01        1
GA01        1
S01         1
FB01        1
R01         1
O01         1
TB01        1
PA01        1
XA01        1
Q01         1
Name: count, dtype: Int64
----------------------------------
 Variable :  place
----------------------------------
 Description
----------------------------------

place
1     94007
2     14453
10     9476
3      2476
4      2228
9      1188
7      1101
5       607
8       437
6       147
Name: count, dtype: Int64
----------------------------------
 Variable :  catu
----------------------------------
 Description
----------------------------------

catu
1    94236
2    22408
3     9476
Name: count, dtype: Int64
----------------------------------
 Variable :  grav
----------------------------------
 Description
----------------------------------

grav
1    52115
4    51697
3    19088
2     3220
Name: count, dtype: Int64
----------------------------------
 Variable :  sexe
----------------------------------
 Description
----------------------------------

sexe
1    86213
2    39897
3       10
Name: count, dtype: Int64
----------------------------------
 Variable :  an_nais
----------------------------------
 Description
----------------------------------

an_nais
2000    4135
2001    4059
1999    3792
2002    3751
1998    3450
        ...
1920       2
1921       1
1789       1
1919       1
2025       1
Name: count, Length: 105, dtype: Int64
----------------------------------
 Variable :  trajet
----------------------------------
 Description
----------------------------------

trajet
5     45432
0     32556
1     17343
4     12185
9     11033
3      4532
2      2832
-1      207
Name: count, dtype: Int64
----------------------------------
 Variable :  secu1
----------------------------------
 Description
----------------------------------

secu1
1     75705
2     23954
8     13391
0     11830
3       821
6       114
9       109
-1       94
4        75
5        24
7         3
Name: count, dtype: Int64
----------------------------------
 Variable :  secu2
----------------------------------
 Description
----------------------------------

secu2
-1    53003
0     46095
6     11656
8     11441
5      1529
4      1381
9       350
1       247
3       149
7       145
2       124
Name: count, dtype: Int64
----------------------------------
 Variable :  secu3
----------------------------------
 Description
----------------------------------

secu3
-1    124807
9        908
0        271
6         78
8         27
4         16
5          5
7          5
2          3
Name: count, dtype: Int64
----------------------------------
 Variable :  locp
----------------------------------
 Description
----------------------------------

locp
-1    61599
0     55234
3      2839
2      2123
4      1403
1      1344
5       757
9       411
6       259
8       139
7        12
Name: count, dtype: Int64
----------------------------------
 Variable :  actp
----------------------------------
 Description
----------------------------------

actp
-1    60108
0     56693
3      6836
9       641
1       610
5       434
2       263
B       244
A       120
4       116
6        26
8        19
7        10
Name: count, dtype: Int64
----------------------------------
 Variable :  etatp
----------------------------------
 Description
----------------------------------

etatp
-1    116815
1       7013
2       1868
3        424
Name: count, dtype: Int64

* **Base vehicules**

In [129]:
df_veh = pd.read_csv("vehicules.csv",sep=";", encoding="latin-1", decimal=",")
df_veh.head(10)

  id_vehicule num_veh  senc  catv  obs  obsm  choc  manv  motor  occutc
0    129åÊ983     A01     1    33    0     2     3     1      1     NaN
1    192åÊ850     B01     1    10    0     2     4     2      1     NaN
2    152åÊ776     A01     1    33    0     2     1     3      3     NaN
3    193åÊ398     A01     1     7    0     1     2     1      1     NaN
4    178åÊ605     A01     2     7    0     1     2     1      1     NaN
5    187åÊ823     A01     2    30    0     2     1     1      1     NaN
6    103åÊ719     B01     1     1    0     2     1     1      5     NaN
7    164åÊ572     B01     1     7    8     2     2     1      1     NaN
8    190åÊ438     B01     3    15    0     2     3     1      1     NaN
9    146åÊ391     B01     1     7    0     2     4     2      1     NaN

In [131]:
df_veh.shape

(97365, 10)

In [73]:
# Modification format id_vehicule

In [74]:
df_veh["id_vehicule"]=df_veh["id_vehicule"].str.replace("åÊ", "A", regex=False)
df_veh.head()

  id_vehicule num_veh  senc  catv  obs  obsm  choc  manv  motor  occutc
0     129A983     A01     1    33    0     2     3     1      1     NaN
1     192A850     B01     1    10    0     2     4     2      1     NaN
2     152A776     A01     1    33    0     2     1     3      3     NaN
3     193A398     A01     1     7    0     1     2     1      1     NaN
4     178A605     A01     2     7    0     1     2     1      1     NaN

**Exploration de la base vehicule**

In [75]:
# Cette commande détecte automatiquement si une colonne doit être int, string, objet ou boolean
df_veh = df_veh.convert_dtypes()

In [76]:
def explore_base(df_veh):
    print("\033[1mFormat\033[0m")
    print("----------------------------------")
    print(df_veh.info())
    print("----------------------------------")
    print("\033[1mContrôle des valeurs manquantes\033[0m")
    print("----------------------------------")
    print(df_veh.isna().sum().sort_values(ascending=False))

    for i in df_veh.columns:
        if df_veh[i].dtypes in ['int64','float64']:
            print("----------------------------------")
            print("\033[1m Variable :\033[0m",i)
            print("----------------------------------")
            print("\033[1m Description \033[0m")
            print("----------------------------------\n")
            print(df_veh[i].describe())
            print("----------------------------------")
            print("\033[1m Modalité \033[0m")
            print("----------------------------------\n")
            print(df_veh[i].unique())

        else:
            print("----------------------------------")
            print("\033[1m Variable : \033[0m",i)
            print("----------------------------------")
            print("\033[1m Description \033[0m")
            print("----------------------------------\n")
            print(df_veh[i].value_counts(dropna=False))

In [77]:
explore_base(df_veh)

Format
----------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97365 entries, 0 to 97364
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_vehicule  97365 non-null  string
 1   num_veh      97365 non-null  string
 2   senc         97365 non-null  Int64
 3   catv         97365 non-null  Int64
 4   obs          97365 non-null  Int64
 5   obsm         97365 non-null  Int64
 6   choc         97365 non-null  Int64
 7   manv         97365 non-null  Int64
 8   motor        97365 non-null  Int64
 9   occutc       744 non-null    Int64
dtypes: Int64(8), string(2)
memory usage: 8.2 MB
None
----------------------------------
Contrôle des valeurs manquantes
----------------------------------
occutc         96621
id_vehicule        0
num_veh            0
senc               0
catv               0
obs                0
obsm               0
choc               0
manv               0
motor              0
dtype: int64
----------------------------------
 Variable :  id_vehicule
----------------------------------
 Description
----------------------------------

id_vehicule
129A983    1
200A350    1
126A055    1
168A102    1
117A981    1
          ..
168A593    1
151A450    1
158A209    1
129A266    1
181A572    1
Name: count, Length: 97365, dtype: Int64
----------------------------------
 Variable :  num_veh
----------------------------------
 Description
----------------------------------

num_veh
A01     55590
B01     34806
C01      3999
Z01      1470
D01       899
E01       267
F01        80
Y01        73
G01        34
T01        24
H01        19
I01        10
X01         9
J01         8
K01         7
M01         5
L01         5
FA01        4
P01         4
[01         4
SA01        4
TA01        3
V01         3
BA01        2
ZZ01        2
MB01        2
AA01        2
VB01        2
RA01        2
DA01        2
CA01        2
U01         1
R01         1
NA01        1
S01         1
EB01        1
SB01        1
Q01         1
PA01        1
GB01        1
KD01        1
GA01        1
FB01        1
IA01        1
LA01        1
XA01        1
TB01        1
KA01        1
O01         1
N01         1
AB01        1
]01         1
YA01        1
Name: count, dtype: Int64
----------------------------------
 Variable :  senc
----------------------------------
 Description
----------------------------------

senc
1     44107
2     33152
3     13658
0      6041
-1      407
Name: count, dtype: Int64
----------------------------------
 Variable :  catv
----------------------------------
 Description
----------------------------------

catv
7     57132
33     7514
10     6748
1      5620
2      3824
30     3382
32     2223
31     1688
50     1510
15      970
34      899
14      734
17      641
37      621
43      612
80      534
3       523
99      438
13      387
21      265
60      237
0       219
36      180
40      133
38      123
20       95
39       41
16       36
35       18
41       11
-1        4
42        3
Name: count, dtype: Int64
----------------------------------
 Variable :  obs
----------------------------------
 Description
----------------------------------

obs
0     83600
1      2295
13     1633
2      1397
4      1290
3      1219
8      1132
6      1064
12      756
14      700
15      563
9       506
16      382
7       283
5       173
11      155
10      110
17       83
-1       24
Name: count, dtype: Int64
----------------------------------
 Variable :  obsm
----------------------------------
 Description
----------------------------------

obsm
2     69082
0     17575
1      8593
9      1741
6       137
4       113
5        86
-1       38
Name: count, dtype: Int64
----------------------------------
 Variable :  choc
----------------------------------
 Description
----------------------------------

choc
1     35089
3     14225
2     11950
4      9760
8      6724
0      6292
7      5793
6      3452
5      2721
9      1315
-1       44
Name: count, dtype: Int64
----------------------------------
 Variable :  manv
----------------------------------
 Description
----------------------------------

manv
1     39508
2     11388
15     8170
0      5578
13     4023
26     3563
17     3251
9      3150
16     2591
19     2573
23     2383
14     1868
21     1465
5      1090
11     1087
12     1015
3      1000
10      665
20      556
18      544
4       414
24      377
22      347
25      306
7       255
6       143
8        35
-1       20
Name: count, dtype: Int64
----------------------------------
 Variable :  motor
----------------------------------
 Description
----------------------------------

motor
1     82081
5      5185
0      4489
3      3232
2      1730
6       456
-1      168
4        24
Name: count, dtype: Int64
----------------------------------
 Variable :  occutc
----------------------------------
 Description
----------------------------------

occutc
<NA>    96621
1         554
2          88
3          49
4          22
5           8
6           5
10          2
0           2
8           2
11          2
7           2
14          2
17          1
13          1
9           1
12          1
28          1
16          1
Name: count, dtype: Int64

## Exporter les bases propres

In [132]:
# Export des 4 bases dans le dossier 'data'
df_caract.to_csv('data/caracteristiques_clean.csv', index=False, sep=';', encoding='utf-8-sig')
df_lieux.to_csv('data/lieux_clean.csv', index=False, sep=';', encoding='utf-8-sig')
df_usag_clean.to_csv('data/usagers_clean.csv', index=False, sep=';', encoding='utf-8-sig')
df_veh_clean.to_csv('data/vehicules_clean.csv', index=False, sep=';', encoding='utf-8-sig')

# la base finale fusionnée
df_final.to_csv('data/base_complete.csv', index=False, sep=';', encoding='utf-8-sig')

print("Félicitations ! Tes 5 fichiers sont bien rangés dans le dossier /data.")

Félicitations ! Tes 5 fichiers sont bien rangés dans le dossier /data.

## Vérification des doublon et nettoyage des données dans chaque base

* **Base caracteristique**

**Traitement des doublons pures et impures**

In [88]:
df_caract.duplicated().sum()

np.int64(11)

In [89]:
#Doublons pure

In [90]:
df_caract[df_caract.duplicated(keep=False)].sort_values("Num_Acc")

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,col,adr,lat,long
33687,202100013498,12,10,2021,11:00,1,CC_71076,2,2,1,3,Avenue de Paris,"46,79438402","4,848719001"
6317,202100013498,12,10,2021,11:00,1,CC_71076,2,2,1,3,Avenue de Paris,"46,79438402","4,848719001"
25206,202100017917,21,9,2021,09:45,1,CC_95280,2,1,1,3,RD 47A,"49,01144865","2,479454682"
19025,202100017917,21,9,2021,09:45,1,CC_95280,2,1,1,3,RD 47A,"49,01144865","2,479454682"
32639,202100023406,19,8,2021,10:00,1,CC_97120,2,1,1,6,UNIVERSITE FOUILLOLE,"16,22706","-61,52962"
420,202100023406,19,8,2021,10:00,1,CC_97120,2,1,1,6,UNIVERSITE FOUILLOLE,"16,22706","-61,52962"
45121,202100027321,23,7,2021,11:10,1,CC_97302,2,1,1,3,A.HENRI(RUE),"4,922661236","-52,3113595"
50662,202100027321,23,7,2021,11:10,1,CC_97302,2,1,1,3,A.HENRI(RUE),"4,922661236","-52,3113595"
2994,202100027995,20,7,2021,18:20,1,CC_62307,2,1,1,1,Route de Peuplingues,"50,914111","1,724478"
55470,202100027995,20,7,2021,18:20,1,CC_62307,2,1,1,1,Route de Peuplingues,"50,914111","1,724478"
7554,202100032369,25,6,2021,17:00,1,CC_43191,1,1,1,7,A75,"45,359021","3,280535"
40541,202100032369,25,6,2021,17:00,1,CC_43191,1,1,1,7,A75,"45,359021","3,280535"
25962,202100034484,15,6,2021,08:40,1,CC_44014,1,3,1,3,Le Gros Caillou,"47,112035","-1,476181"
41559,202100034484,15,6,2021,08:40,1,CC_44014,1,3,1,3,Le Gros Caillou,"47,112035","-1,476181"
20493,202100045186,4,4,2021,19:25,1,CC_49321,1,1,1,6,A11 pk 296+492,"47,427173","-0,930727"
1588,202100045186,4,4,2021,19:25,1,CC_49321,1,1,1,6,A11 pk 296+492,"47,427173","-0,930727"
45931,202100049552,2,3,2021,07:00,2,CC_61256,1,1,1,7,a 88 PK 010+100,"48,663536","0,06772"
8475,202100049552,2,3,2021,07:00,2,CC_61256,1,1,1,7,a 88 PK 010+100,"48,663536","0,06772"
17470,202100051453,15,2,2021,08:40,1,CC_75113,2,1,8,7,AVENUE D IVRY,"48,824631","2,363093"
51196,202100051453,15,2,2021,08:40,1,CC_75113,2,1,8,7,AVENUE D IVRY,"48,824631","2,363093"
17015,202100052300,2,2,2021,13:35,1,CC_74281,2,1,2,6,CORNICHE (BD DE LA) INFERIEUR N°20,"46,37226","6,4741"
29819,202100052300,2,2,2021,13:35,1,CC_74281,2,1,2,6,CORNICHE (BD DE LA) INFERIEUR N°20,"46,37226","6,4741"

In [91]:
#Doublons inpures

In [92]:
df_caract[df_caract.duplicated(subset=["Num_Acc"], keep=False)].sort_values("Num_Acc")

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,col,adr,lat,long
33687,202100013498,12,10,2021,11:00,1,CC_71076,2,2,1,3,Avenue de Paris,"46,79438402","4,848719001"
6317,202100013498,12,10,2021,11:00,1,CC_71076,2,2,1,3,Avenue de Paris,"46,79438402","4,848719001"
25206,202100017917,21,9,2021,09:45,1,CC_95280,2,1,1,3,RD 47A,"49,01144865","2,479454682"
19025,202100017917,21,9,2021,09:45,1,CC_95280,2,1,1,3,RD 47A,"49,01144865","2,479454682"
32639,202100023406,19,8,2021,10:00,1,CC_97120,2,1,1,6,UNIVERSITE FOUILLOLE,"16,22706","-61,52962"
420,202100023406,19,8,2021,10:00,1,CC_97120,2,1,1,6,UNIVERSITE FOUILLOLE,"16,22706","-61,52962"
45121,202100027321,23,7,2021,11:10,1,CC_97302,2,1,1,3,A.HENRI(RUE),"4,922661236","-52,3113595"
50662,202100027321,23,7,2021,11:10,1,CC_97302,2,1,1,3,A.HENRI(RUE),"4,922661236","-52,3113595"
2994,202100027995,20,7,2021,18:20,1,CC_62307,2,1,1,1,Route de Peuplingues,"50,914111","1,724478"
55470,202100027995,20,7,2021,18:20,1,CC_62307,2,1,1,1,Route de Peuplingues,"50,914111","1,724478"
7554,202100032369,25,6,2021,17:00,1,CC_43191,1,1,1,7,A75,"45,359021","3,280535"
40541,202100032369,25,6,2021,17:00,1,CC_43191,1,1,1,7,A75,"45,359021","3,280535"
25962,202100034484,15,6,2021,08:40,1,CC_44014,1,3,1,3,Le Gros Caillou,"47,112035","-1,476181"
41559,202100034484,15,6,2021,08:40,1,CC_44014,1,3,1,3,Le Gros Caillou,"47,112035","-1,476181"
20493,202100045186,4,4,2021,19:25,1,CC_49321,1,1,1,6,A11 pk 296+492,"47,427173","-0,930727"
1588,202100045186,4,4,2021,19:25,1,CC_49321,1,1,1,6,A11 pk 296+492,"47,427173","-0,930727"
45931,202100049552,2,3,2021,07:00,2,CC_61256,1,1,1,7,a 88 PK 010+100,"48,663536","0,06772"
8475,202100049552,2,3,2021,07:00,2,CC_61256,1,1,1,7,a 88 PK 010+100,"48,663536","0,06772"
17470,202100051453,15,2,2021,08:40,1,CC_75113,2,1,8,7,AVENUE D IVRY,"48,824631","2,363093"
51196,202100051453,15,2,2021,08:40,1,CC_75113,2,1,8,7,AVENUE D IVRY,"48,824631","2,363093"
17015,202100052300,2,2,2021,13:35,1,CC_74281,2,1,2,6,CORNICHE (BD DE LA) INFERIEUR N°20,"46,37226","6,4741"
29819,202100052300,2,2,2021,13:35,1,CC_74281,2,1,2,6,CORNICHE (BD DE LA) INFERIEUR N°20,"46,37226","6,4741"

**Commentaire :**  Dans la base caracteristique, je constate la présence de **11** doublons

In [93]:
# Supprime les doublons en gardant la première occurrence
df_caract = df_caract.drop_duplicates(subset=["Num_Acc"], keep='first')

In [94]:
df_caract[df_caract.duplicated(subset=["Num_Acc"], keep=False)].sort_values("Num_Acc")

Empty DataFrame
Columns: [Num_Acc, jour, mois, an, hrmn, lum, com, agg, int, atm, col, adr, lat, long]
Index: []

In [95]:
df_caract[df_caract.duplicated(keep=False)].sort_values("Num_Acc")

Empty DataFrame
Columns: [Num_Acc, jour, mois, an, hrmn, lum, com, agg, int, atm, col, adr, lat, long]
Index: []

In [96]:
df_caract.duplicated().sum()

np.int64(0)

In [97]:
print(df_caract.Num_Acc.nunique())
#print(df_caract.shape)

56519

In [98]:
df_caract_clean=df_caract
df_caract_clean

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,col,adr,lat,long
0,202100037733,28,5,2021,14:15,1,CC_97407,2,2,1,3,JEAN MOULIN (RUE) - RIV. DES GALETS,"-20,95888","55,31743"
1,202100049382,2,3,2021,10:59,1,CC_63113,2,1,1,2,SAINT ROBERT (RUE),"45,79137","3,1162"
2,202100038891,20,5,2021,16:50,1,CC_88160,2,2,1,1,POISSOMPRE (FG DE),"48,18261","6,47218"
3,202100028616,14,7,2021,19:45,1,CC_80021,2,1,1,3,CAGNARD (RUE),"49,90355","2,2872"
4,202100033509,17,6,2021,23:40,3,CC_13214,2,1,1,1,A7-Sens Lyon vers Marseille,"43,34031","5,37689"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56525,202100026753,28,7,2021,17:10,1,CC_38474,2,2,1,3,Rue du Vinay,"45,204957","5,667561"
56526,202100019814,10,9,2021,06:15,3,CC_77251,1,1,1,7,RN 104,"48,631","2,533"
56527,202100016048,29,9,2021,08:15,1,CC_78524,1,1,1,3,A13,"48,841059","2,106997"
56528,202100039830,15,5,2021,06:45,2,CC_13212,2,2,1,3,PIERRE CHEVALIER (avenue),"43,2953","5,4254"
56529,202100046742,13,3,2021,09:30,1,CC_76108,2,1,2,7,HAIE. RUE DE LA,"49,46523106","1,112713775"

* **Base lieux**

In [99]:
df_lieux.duplicated().sum()

np.int64(0)

**Commentaire :**  Dans la base lieux, je constate la présence de **0** doublons

**Remplacer *v2* par une valeur par défaut (Imputation)**

Pour les colonnes textuelles comme voie tel que **v2** qui est la lettre de l'indice alphanumérique de la route est importante, donc j'ai remplacé par "Inconnu"

In [100]:
df_lieux["v2"] = df_lieux["v2"].fillna("Inconnu")
df_lieux["v2"]

0              A
1        Inconnu
2              T
3        Inconnu
4        Inconnu
          ...
56520    Inconnu
56521    Inconnu
56522    Inconnu
56523    Inconnu
56524    Inconnu
Name: v2, Length: 56525, dtype: object

In [101]:
print(df_lieux["v2"].value_counts())

v2
Inconnu    51535
D           3164
A            896
N            225
C            119
E            106
R             92
B             85
M             74
 -            67
T             43
F             24
X             15
V             14
O             12
U              9
G              8
S              7
Z              6
L              5
P              5
H              3
K              3
J              3
W              2
I              2
34             1
Name: count, dtype: int64

**Gérer les NaN de la colonnes lartpc**

si **lartpc** est la largeur du terre-plein central (TPC) s'il existe (en m), contient plus de 80% de **NaN**, elle n'apporte aucune valeur statistique. Donc je l'ai supprimé

In [104]:
df_lieux.columns

Index(['Num_Acc', 'dep', 'catr', 'voie', 'v1', 'v2', 'circ', 'nbv', 'vosp',
       'prof', 'pr', 'pr1', 'plan', 'larrout', 'surf', 'infra', 'situ', 'vma'],
      dtype='object')

In [105]:
# Calcul du pourcentage de NaN pour lartpc
#pct_nan_lartpc = df_lieux['lartpc'].isnull().mean() * 100

#print(f"Le pourcentage de valeurs manquantes dans 'lartpc' est de : {pct_nan_lartpc:.2f}%")

In [ ]:
# Supprime les colonnes qui ont trop de vides
limit = len(df_lieux) * 0.5  # Seuil de 50%
df_lieux = df_lieux.dropna(thresh=limit, axis=1)

In [106]:
df_lieux_clean=df_lieux
df_lieux_clean

,Num_Acc,dep,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,larrout,surf,infra,situ,vma
0,202100022009,40,1,A63,0,A,3,3,0,1,141,600,1,-1.0,1,0,1,130
1,202100023746,94,4,VLADIMIR ILLITCH LENINE (AV),0,Inconnu,-1,2,0,1,0,0,1,-1.0,1,0,1,50
2,202100019549,2A,2,20,0,T,2,2,0,1,-1,-1,2,-1.0,1,0,3,80
3,202100022748,75,4,AVENUE SIMON BOLIVAR,0,Inconnu,2,2,0,2,-1,-1,1,-1.0,1,0,1,50
4,202100051993,971,3,BOLOGNE (ROUTE DE),0,Inconnu,2,2,0,1,-1,-1,1,-1.0,1,0,1,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56520,202100056035,76,4,LYONS. ROUTE DE (BRETELLE C),0,Inconnu,1,2,0,1,-1,-1,1,-1.0,1,-1,1,30
56521,202100043915,75,4,RUE LOUIS BLANC,0,Inconnu,1,2,0,1,-1,-1,1,-1.0,1,0,1,30
56522,202100047332,73,4,JEUX OLYMPIQUES (AVENUE DES),0,Inconnu,3,2,2,1,-1,-1,1,-1.0,1,-1,1,50
56523,202100016135,64,4,SERGENT BERNES CAMBOT DU,0,Inconnu,2,3,1,1,0,0,1,-1.0,1,0,1,30
56524,202100017773,78,2,RN12,0,Inconnu,3,4,0,1,28,799,1,-1.0,1,0,1,110

* **Base usagers**

**Traitement des doublons pures et impures**

In [107]:
df_usag.duplicated().sum()

np.int64(33)

**Commentaire :** Dans la base usagers, je constate la présence de 33 doublons

In [108]:
#Doublons pures
df_usag[df_usag.duplicated(keep=False)].sort_values("Num_Acc")

,Num_Acc,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
72758,202100001471,199A 156,B01,1,1,1,1,1995,9,1,0,-1,-1,-1,-1
55476,202100001471,199A 156,B01,1,1,1,1,1995,9,1,0,-1,-1,-1,-1
28399,202100003260,195A 936,A01,10,3,4,2,2002,5,0,-1,-1,3,3,2
108756,202100003260,195A 936,A01,10,3,4,2,2002,5,0,-1,-1,3,3,2
77041,202100006907,189A 424,A01,2,2,4,1,1998,5,1,0,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78604,202100050391,111A 622,B01,1,1,1,1,1975,4,1,-1,-1,0,0,-1
118307,202100052378,108A 090,B01,1,1,4,1,2001,0,2,0,-1,-1,-1,-1
48087,202100052378,108A 090,B01,1,1,4,1,2001,0,2,0,-1,-1,-1,-1
9691,202100052486,107A 904,A01,1,1,3,1,1990,5,1,-1,-1,0,0,-1
24115,202100052486,107A 904,A01,1,1,3,1,1990,5,1,-1,-1,0,0,-1

In [109]:
# Supprime les doublons en gardant la première occurrence
df_usag = df_usag.drop_duplicates(subset=["Num_Acc"], keep='first')
df_usag.duplicated().sum()

np.int64(0)

In [110]:
df_usag[df_usag.duplicated(keep=False)].sort_values("Num_Acc")

Empty DataFrame
Columns: [Num_Acc, id_vehicule, num_veh, place, catu, grav, sexe, an_nais, trajet, secu1, secu2, secu3, locp, actp, etatp]
Index: []

In [111]:
#df_usag.copy()

In [112]:
#Doublons inpures
df_usag[df_usag.duplicated(subset=["Num_Acc"], keep=False)].sort_values("Num_Acc")

Empty DataFrame
Columns: [Num_Acc, id_vehicule, num_veh, place, catu, grav, sexe, an_nais, trajet, secu1, secu2, secu3, locp, actp, etatp]
Index: []

In [113]:
# Pour voir s'il y a des vraies erreurs (même accident, même véhicule, même place)
df_usag[df_usag.duplicated(subset=["Num_Acc", "num_veh", "id_vehicule", "place", "an_nais", "sexe"], keep=False)]

Empty DataFrame
Columns: [Num_Acc, id_vehicule, num_veh, place, catu, grav, sexe, an_nais, trajet, secu1, secu2, secu3, locp, actp, etatp]
Index: []

In [128]:
print(df_usag.id_vehicule.nunique())
print(df_usag.shape)

56518
(56521, 15)

In [115]:
df_usag_clean=df_usag
df_usag_clean

,Num_Acc,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,202100021165,163A 830,A01,9,2,4,1,1948,0,1,-1,-1,0,0,-1
1,202100020281,165A 383,A01,1,1,1,2,1965,1,1,8,-1,-1,-1,-1
2,202100047336,117A 153,A01,1,1,4,2,1972,0,2,0,-1,-1,-1,-1
3,202100008918,185A 779,B01,1,1,4,1,1985,9,8,0,-1,-1,-1,-1
4,202100009175,185A 315,A01,1,1,3,1,1960,5,1,-1,-1,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129149,202100055940,101A 892,A01,1,1,4,1,1989,1,2,6,-1,0,0,-1
129173,202100054777,103A 879,A01,1,1,2,2,1935,5,1,0,-1,0,0,-1
129186,202100056519,163A 830,A01,9,2,4,1,1948,0,1,-1,-1,0,0,-1
129187,202100056520,165A 383,A01,1,1,1,2,1965,1,1,8,-1,-1,-1,-1
129188,202100056521,117A 153,A01,1,1,4,2,1972,0,2,0,-1,-1,-1,-1

* **Base vehicules**

In [116]:
df_veh.duplicated().sum()

np.int64(0)

**Commentaire :**  Dans la base vehicule, je constate la présence de **0** doublons

In [117]:
# Vérifier s'il y a au moins une valeur remplie
print(df_veh['occutc'].notnull().sum())

744

In [118]:
# Remplacer les NaN par 0
df_veh['occutc'] = df_veh['occutc'].fillna(0)

# Convertir en entier (pour enlever le .0)
df_veh['occutc'] = df_veh['occutc'].astype(int)

In [119]:
df_veh_clean=df_veh
df_veh_clean

      id_vehicule num_veh  senc  catv  obs  obsm  choc  manv  motor  occutc
0         129A983     A01     1    33    0     2     3     1      1       0
1         192A850     B01     1    10    0     2     4     2      1       0
2         152A776     A01     1    33    0     2     1     3      3       0
3         193A398     A01     1     7    0     1     2     1      1       0
4         178A605     A01     2     7    0     1     2     1      1       0
...           ...     ...   ...   ...  ...   ...   ...   ...    ...     ...
97360     108A341     A01     1     1    0     0     0     1      5       0
97361     200A693     B01     1     1    0     2     5    26      5       0
97362     192A529     B01     1    31    0     2     1     1      1       0
97363     174A733     B01     1     2    0     2     3     1      1       0
97364     181A572     B01     1     2    0     0     4     2      1       0

[97365 rows x 10 columns]

In [120]:
df_veh[df_veh['occutc']!=0]

      id_vehicule num_veh  senc  catv  obs  obsm  choc  manv  motor  occutc
74        172A370     A01     1    37    0     2     3     0      1       1
125       145A258     B01     1    37    0     2     6     1      1       1
224       154A771     B01     1    37    0     2     7     1      1       1
262       178A037     B01     2    37    0     2     4     1      1       1
278       110A314     B01     2    38    0     2     3     1      1       1
...           ...     ...   ...   ...  ...   ...   ...   ...    ...     ...
97025     130A817     B01     2    37    0     2     8     0      1       1
97112     151A326     A01     1    37    0     2     3    19      1       4
97150     155A428     B01     1    37    0     0     8    15      1       1
97184     179A775     B01     2    37    0     2     4    23      6       1
97235     102A152     B01     1    37    0     2     2     1      0       1

[742 rows x 10 columns]

**Test de correlation**

In [121]:
#tableau de contingence(tableau croisé)
tab=pd.crosstab(df_veh_clean.id_vehicule,df_veh_clean.senc) #tableau de contingence(tableau croisé)
tab

senc         -1  0   1   2   3
id_vehicule
100A882       0   0   0   1   0
100A883       0   0   1   0   0
100A884       0   0   0   1   0
100A885       0   0   1   0   0
100A886       0   0   0   1   0
...          ..  ..  ..  ..  ..
206A069       0   0   1   0   0
206A070       0   0   1   0   0
206A071       0   0   1   0   0
206A072       0   0   0   0   1
206A073       0   0   0   0   1

[97365 rows x 5 columns]

In [122]:
# P-value de test de fisher
#oddsratio, p_value = fisher_exact(tab)
#oddsratio, p_value

In [123]:
#test de Khi-deux
#chi2, p_value, dof, expectid= chi2_contingency(tab)

In [124]:
#Résultat test
#chi2, p_value, dof, expectid

# Jointure des bases

La **gravité** donne du sens aux fusions (merges) que je vais faire :

**Lieux** + Gravité : Quelles infrastructures sont les plus meurtrières ?

**Véhicules** + Gravité : Les airbags ou la taille du véhicule protègent-ils réellement ?

**Usagers** + Gravité : Quel est l'impact de l'âge ou de la position dans la voiture ?

**Caracteristique** + Gravité : quel est l'état réel de la voiture au moment de l'accident ?

In [127]:
print(df_caract_clean.shape)
print(df_lieux_clean.shape)
print(df_usag_clean.shape)
print(df_veh_clean.shape)

(56519, 14)
(56525, 18)
(56521, 15)
(97365, 10)

In [83]:
# Jointure des tables df_caract et  df_lieux
df_caract_lieux= df_caract_clean.merge(df_lieux_clean,left_on="Num_Acc",right_on="Num_Acc",how="inner")
df_caract_lieux.head()

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,...,vosp,prof,pr,pr1,plan,larrout,surf,infra,situ,vma
0,202100037733,28,5,2021,14:15,1,CC_97407,2,2,1,...,0,1,0,0,1,-1.0,1,5,1,50
1,202100049382,2,3,2021,10:59,1,CC_63113,2,1,1,...,0,1,0,0,1,-1.0,1,0,1,50
2,202100038891,20,5,2021,16:50,1,CC_88160,2,2,1,...,0,1,0,920,1,-1.0,1,0,1,50
3,202100028616,14,7,2021,19:45,1,CC_80021,2,1,1,...,0,4,-1,-1,1,-1.0,1,0,1,50
4,202100033509,17,6,2021,23:40,3,CC_13214,2,1,1,...,0,2,279,0,2,-1.0,1,0,1,70

In [47]:
df_caract_lieux.shape

(56526, 31)

In [64]:
df_caract_lieux[(df_caract_lieux["Num_Acc"].isna())]

Empty DataFrame
Columns: [Num_Acc, jour, mois, an, hrmn, lum, com, agg, int, atm, col, adr, lat, long, dep, catr, voie, v1, v2, circ, nbv, vosp, prof, pr, pr1, plan, larrout, surf, infra, situ, vma]
Index: []

[0 rows x 31 columns]

In [100]:
# Jointure des tables df_caract_lieux et df_usag_clean
df_caract_lieux_usag= df_caract_lieux.merge(df_usag_clean,left_on="Num_Acc",right_on="Num_Acc",how="inner")
df_caract_lieux_usag.head()

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,...,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,202100037733,28,5,2021,14:15,1,CC_97407,2,2,1,...,4,1,1970,0,8,8,-1,-1,-1,-1
1,202100049382,2,3,2021,10:59,1,CC_63113,2,1,1,...,1,1,1979,1,1,0,-1,0,0,-1
2,202100038891,20,5,2021,16:50,1,CC_88160,2,2,1,...,1,1,1931,5,1,0,-1,-1,-1,-1
3,202100028616,14,7,2021,19:45,1,CC_80021,2,1,1,...,4,2,1973,0,1,-1,-1,0,0,-1
4,202100033509,17,6,2021,23:40,3,CC_13214,2,1,1,...,1,1,2002,5,1,0,-1,-1,-1,-1

In [121]:
df_caract_lieux_usag.shape

(56525, 45)

In [122]:
df_caract_lieux_usag[(df_caract_lieux_usag["Num_Acc"].isna())]

Empty DataFrame
Columns: [Num_Acc, jour, mois, an, hrmn, lum, com, agg, int, atm, col, adr, lat, long, dep, catr, voie, v1, v2, circ, nbv, vosp, prof, pr, pr1, plan, larrout, surf, infra, situ, vma, id_vehicule, num_veh, place, catu, grav, sexe, an_nais, trajet, secu1, secu2, secu3, locp, actp, etatp]
Index: []

[0 rows x 45 columns]

In [116]:
# Affiche les données et le type (dtype) en bas de la liste
df_caract_lieux_usag['id_vehicule']

0        134A 220
1        113A 491
2        132A 115
3        150A 566
4        141A 884
           ...
56520    153A 902
56521    166A 228
56522    172A 966
56523    130A 384
56524    118A 220
Name: id_vehicule, Length: 56525, dtype: object

In [115]:
df_veh['id_vehicule']

0        129A983
1        192A850
2        152A776
3        193A398
4        178A605
          ...
97360    108A341
97361    200A693
97362    192A529
97363    174A733
97364    181A572
Name: id_vehicule, Length: 97365, dtype: object

In [118]:
# Nettoyage des espaces internes et mise en majuscules pour les deux tables
df_caract_lieux_usag['id_vehicule'] = df_caract_lieux_usag['id_vehicule'].astype(str).str.replace(r'\s+', '', regex=True).str.upper()
df_veh['id_vehicule'] = df_veh['id_vehicule'].astype(str).str.replace(r'\s+', '', regex=True).str.upper()

Le symbole **\s+** en expression régulière (**regex=True**) détecte tous les caractères "blancs" (espaces, tabulations, retours à la ligne) et les supprime.

In [124]:
# la jointure des 4 bases de données
df_final = df_caract_lieux_usag.merge(df_veh, on='id_vehicule', how='inner')

print(f"Nombre de lignes dans la base finale : {len(df_final)}")

Nombre de lignes dans la base finale : 56525

In [123]:
#Affichage de la jointure de la base finale
df_final

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,...,etatp,num_veh_y,senc,catv,obs,obsm,choc,manv,motor,occutc
0,202100037733,28,5,2021,14:15,1,CC_97407,2,2,1,...,-1,B01,3,1,0,2,8,1,5,0
1,202100049382,2,3,2021,10:59,1,CC_63113,2,1,1,...,-1,A01,1,10,0,2,1,2,1,0
2,202100038891,20,5,2021,16:50,1,CC_88160,2,2,1,...,-1,A01,1,7,0,2,1,1,1,0
3,202100028616,14,7,2021,19:45,1,CC_80021,2,1,1,...,-1,A01,0,7,0,2,1,15,1,0
4,202100033509,17,6,2021,23:40,3,CC_13214,2,1,1,...,-1,A01,2,7,4,5,1,26,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56520,202100026753,28,7,2021,17:10,1,CC_38474,2,2,1,...,-1,A01,2,1,0,2,2,0,5,0
56521,202100019814,10,9,2021,06:15,3,CC_77251,1,1,1,...,-1,A01,2,34,0,5,7,21,1,0
56522,202100016048,29,9,2021,08:15,1,CC_78524,1,1,1,...,-1,A01,2,33,0,2,3,3,1,0
56523,202100039830,15,5,2021,06:45,2,CC_13212,2,2,1,...,-1,A01,3,10,0,2,1,1,0,0
56524,202100046742,13,3,2021,09:30,1,CC_76108,2,1,2,...,-1,A01,1,7,0,1,1,16,1,0

## Constituer les bases de train et test

**la préparation de ta variable cible**

Dans le jeu de données BAAC, la colonne grav (gravité) possède 4 modalités :

1 : Indemne

2 : Tué

3 : Blessé hospitalisé

4 : Blessé léger

Pour le modèle de **Machine Learning**, il est souvent préférable de simplifier cela en une classification binaire (Grave vs Non-Grave).

In [125]:
# Vérification de la distribution de la gravité
print("Répartition des classes de gravité :")
print(df_final['grav'].value_counts())

# Vérification du nombre total de lignes et colonnes
print(f"\nDimensions finales : {df_final.shape}")

Répartition des classes de gravité :
grav
4     23403
1     21267
3      9989
2      1848
-1       18
Name: count, dtype: Int64

Dimensions finales : (56525, 54)

**Création de la variable binaire**

Selon la nomenclature officielle, nous avons isoler les conséquences les plus lourdes :

- Grave (1) : Tués (2) et Blessés hospitalisés (3),

- Non-Grave (0) : Indemnes (1) et Blessés légers (4).

In [127]:
# Création de la fonction de mapping
def mapping_gravite(val):
    if val in [2, 3]: # Tué ou Blessé hospitalisé
        return 1
    else: # Indemne ou Blessé léger
        return 0

# Application sur une nouvelle colonne 'target'
df_final['target'] = df_final['grav'].apply(mapping_gravite)

# Vérification du nouvel équilibre
print("Répartition de la variable cible (Target) :")
print(df_final['target'].value_counts(normalize=True) * 100)

Répartition de la variable cible (Target) :
target
0    79.058824
1    20.941176
Name: proportion, dtype: float64

In [128]:
# On ne garde que les colonnes numériques ou catégorielles encodées
# On supprime les identifiants et les colonnes textuelles (comme 'adr')
cols_exclues = ['Num_Acc', 'id_vehicule', 'num_veh', 'adr', 'grav']
df_prep = df_final.drop(columns=[c for c in cols_exclues if c in df_final.columns])

# Gestion des valeurs manquantes (remplacement par le mode ou 0)
df_prep = df_prep.fillna(0) 

# Conversion des colonnes "object" en catégories (si nécessaire)
for col in df_prep.select_dtypes(include=['object']).columns:
    df_prep[col] = df_prep[col].astype('category').cat.codes

In [130]:


# X = les caractéristiques (météo, route, véhicule)
# y = la cible (target : 0 ou 1)
X = df_prep.drop(columns=['target'])
y = df_prep['target']

# Division 80% Train / 20% Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

print(f"Base d'entraînement : {X_train.shape[0]} accidents")
print(f"Base de test : {X_test.shape[0]} accidents")

Base d'entraînement : 45220 accidents
Base de test : 11305 accidents

In [131]:
# Sauvegarde pour ne pas perdre le split
X_train.to_csv('data/X_train.csv', index=False)
X_test.to_csv('data/X_test.csv', index=False)
y_train.to_csv('data/y_train.csv', index=False)
y_test.to_csv('data/y_test.csv', index=False)

print("Tes bases de Train et Test sont prêtes dans le dossier /data !")

Tes bases de Train et Test sont prêtes dans le dossier /data !